//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.06.27 at 09:42:16 PM IST 
//


package com.dds.test;


/**
 * Java content class for DBDetails element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/JAVA_FINAL/JAXB_Table/src/com/dds/test/db.xsd line 2)
 * <p>
 * <pre>
 * &lt;element name="DBDetails">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="DataSourceInfo" type="{}DSInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="TableInfo" type="{}TableInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface DBDetails
    extends javax.xml.bind.Element, com.dds.test.DBDetailsType
{


}
