//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.06.27 at 09:42:16 PM IST 
//


package com.dds.test;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dds.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.dds.test.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.dds.test.impl.runtime.GrammarInfo grammarInfo = new com.dds.test.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.dds.test.ObjectFactory.class));
    public final static java.lang.Class version = (com.dds.test.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.dds.test.TableType.class), "com.dds.test.impl.TableTypeImpl");
        defaultImplementations.put((com.dds.test.DBDetailsType.class), "com.dds.test.impl.DBDetailsTypeImpl");
        defaultImplementations.put((com.dds.test.DSInfoType.class), "com.dds.test.impl.DSInfoTypeImpl");
        defaultImplementations.put((com.dds.test.TableInfoType.class), "com.dds.test.impl.TableInfoTypeImpl");
        defaultImplementations.put((com.dds.test.FieldType.class), "com.dds.test.impl.FieldTypeImpl");
        defaultImplementations.put((com.dds.test.DBDetails.class), "com.dds.test.impl.DBDetailsImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "DBDetails"), (com.dds.test.DBDetails.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dds.test
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of TableType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.TableType createTableType()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.TableTypeImpl();
    }

    /**
     * Create an instance of DBDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.DBDetailsType createDBDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.DBDetailsTypeImpl();
    }

    /**
     * Create an instance of DSInfoType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.DSInfoType createDSInfoType()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.DSInfoTypeImpl();
    }

    /**
     * Create an instance of TableInfoType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.TableInfoType createTableInfoType()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.TableInfoTypeImpl();
    }

    /**
     * Create an instance of FieldType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.FieldType createFieldType()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.FieldTypeImpl();
    }

    /**
     * Create an instance of DBDetails
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.dds.test.DBDetails createDBDetails()
        throws javax.xml.bind.JAXBException
    {
        return new com.dds.test.impl.DBDetailsImpl();
    }

}
