//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.23 at 09:32:58 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/rrs/corona/metricevent")
package com.rrs.corona.metricevent;
