//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.19 at 11:52:33 PM IST 
//


package com.rrs.corona;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Workarea/JAXB_V4/src/example/example.xsd line 11)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;choice>
 *           &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="speedDial" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;/choice>
 *         &lt;group ref="{}ModelGroupChoice"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FooBarType {


    /**
     * Gets the value of the value property.
     * 
     */
    int getValue();

    /**
     * Sets the value of the value property.
     * 
     */
    void setValue(int value);

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getComment();

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setComment(java.lang.String value);

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPhoneNumber();

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPhoneNumber(java.lang.String value);

    /**
     * Gets the value of the bool property.
     * 
     */
    boolean isBool();

    /**
     * Sets the value of the bool property.
     * 
     */
    void setBool(boolean value);

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getZip();

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setZip(java.lang.String value);

    /**
     * Gets the value of the foo property.
     * 
     */
    int getFoo();

    /**
     * Sets the value of the foo property.
     * 
     */
    void setFoo(int value);

    /**
     * Gets the value of the speedDial property.
     * 
     */
    int getSpeedDial();

    /**
     * Sets the value of the speedDial property.
     * 
     */
    void setSpeedDial(int value);

}
