//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.19 at 11:52:33 PM IST 
//


package com.rrs.corona;


/**
 * Java content class for FooBar element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Workarea/JAXB_V4/src/example/example.xsd line 10)
 * <p>
 * <pre>
 * &lt;element name="FooBar">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="foo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;choice>
 *             &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="speedDial" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;/choice>
 *           &lt;group ref="{}ModelGroupChoice"/>
 *         &lt;/sequence>
 *         &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface FooBar
    extends javax.xml.bind.Element, com.rrs.corona.FooBarType
{


}
