//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.19 at 12:52:39 PM IST 
//


package com.vps.dds.jax;


/**
 * Java content class for DatabaseConfig element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/XMLDev/XmlJaxb_V1/src/com/vps/dds/jax/databseconfig.xsd line 5)
 * <p>
 * <pre>
 * &lt;element name="DatabaseConfig">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="database" type="{}databaseType"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface DatabaseConfig
    extends javax.xml.bind.Element, com.vps.dds.jax.DatabaseConfigType
{


}
