//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.19 at 12:52:39 PM IST 
//


package com.vps.dds.jax;


/**
 * Java content class for dbUserType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/XMLDev/XmlJaxb_V1/src/com/vps/dds/jax/databseconfig.xsd line 25)
 * <p>
 * <pre>
 * &lt;complexType name="dbUserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}user"/>
 *         &lt;element ref="{}password"/>
 *         &lt;element name="tableInfo" type="{}tableInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DbUserType {


    /**
     * Gets the value of the tableInfo property.
     * 
     * @return
     *     possible object is
     *     {@link com.vps.dds.jax.TableInfoType}
     */
    com.vps.dds.jax.TableInfoType getTableInfo();

    /**
     * Sets the value of the tableInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vps.dds.jax.TableInfoType}
     */
    void setTableInfo(com.vps.dds.jax.TableInfoType value);

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPassword();

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPassword(java.lang.String value);

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUser();

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUser(java.lang.String value);

}
