//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.30 at 09:05:03 PM IST 
//


package com.rrs.corona.test;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.rrs.corona.test.Info;


/**
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "desgn",
    "adrs"
})
@XmlRootElement(name = "Info")
public class Info {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Desgn")
    protected String desgn;
    @XmlElement(name = "Adrs")
    protected String adrs;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the desgn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesgn() {
        return desgn;
    }

    /**
     * Sets the value of the desgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesgn(String value) {
        this.desgn = value;
    }

    /**
     * Gets the value of the adrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrs() {
        return adrs;
    }

    /**
     * Sets the value of the adrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrs(String value) {
        this.adrs = value;
    }

}
