//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.31 at 09:42:24 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/rrs/corona/empinfo")
package com.rrs.corona;
