//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.20 at 11:32:48 AM IST 
//


package com.rrs.corona;


/**
 * Java content class for addressBook element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Workarea/JAXB_V5/src/contact/contact.xsd line 10)
 * <p>
 * <pre>
 * &lt;element name="addressBook">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}contact" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface AddressBook
    extends javax.xml.bind.Element, com.rrs.corona.AddressBookType
{


}
