//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 10:54:55 PM IST 
//


package example;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Works/TestJAXB_V1/bind-choice/example.xsd line 11)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;choice>
 *           &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="speedDial" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;/choice>
 *         &lt;group ref="{}ModelGroupChoice"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FooBarType {


    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getZip();

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setZip(java.lang.String value);

    /**
     * Gets the value of the phoneNumberOrSpeedDial property.
     * 
     * @return
     *     possible object is
     *     {@link example.FooBarType.PhoneNumberOrSpeedDial}
     */
    example.FooBarType.PhoneNumberOrSpeedDial getPhoneNumberOrSpeedDial();

    /**
     * Sets the value of the phoneNumberOrSpeedDial property.
     * 
     * @param value
     *     allowed object is
     *     {@link example.FooBarType.PhoneNumberOrSpeedDial}
     */
    void setPhoneNumberOrSpeedDial(example.FooBarType.PhoneNumberOrSpeedDial value);

    /**
     * Gets the value of the foo property.
     * 
     */
    int getFoo();

    /**
     * Sets the value of the foo property.
     * 
     */
    void setFoo(int value);

    /**
     * Gets the value of the modelGroupChoice property.
     * 
     * @return
     *     possible object is
     *     {@link example.ModelGroupChoice}
     */
    example.ModelGroupChoice getModelGroupChoice();

    /**
     * Sets the value of the modelGroupChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link example.ModelGroupChoice}
     */
    void setModelGroupChoice(example.ModelGroupChoice value);


    /**
     * Java content class for model group.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Works/TestJAXB_V1/bind-choice/example.xsd line 14)
     * <p>
     * <pre>
     * &lt;choice>
     *   &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *   &lt;element name="speedDial" type="{http://www.w3.org/2001/XMLSchema}int"/>
     * &lt;/choice>
     * </pre>
     * 
     */
    public interface PhoneNumberOrSpeedDial {


        /**
         * Gets the value of the phoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPhoneNumber();

        /**
         * Sets the value of the phoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPhoneNumber(java.lang.String value);

        boolean isSetPhoneNumber();

        /**
         * Gets the value of the speedDial property.
         * 
         */
        int getSpeedDial();

        /**
         * Sets the value of the speedDial property.
         * 
         */
        void setSpeedDial(int value);

        boolean isSetSpeedDial();

        java.io.Serializable getContent();

        boolean isSetContent();

        void unsetContent();

    }

}
