//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 10:54:55 PM IST 
//


package example;


/**
 * Java content class for ModelGroupChoice model group declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Works/TestJAXB_V1/bind-choice/example.xsd line 24)
 * <p>
 * <pre>
 * &lt;group name="ModelGroupChoice">
 *   &lt;choice>
 *     &lt;element name="bool" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *     &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *     &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *   &lt;/choice>
 * &lt;/group>
 * </pre>
 * 
 */
public interface ModelGroupChoice {


    /**
     * Gets the value of the value property.
     * 
     */
    int getValue();

    /**
     * Sets the value of the value property.
     * 
     */
    void setValue(int value);

    boolean isSetValue();

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getComment();

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setComment(java.lang.String value);

    boolean isSetComment();

    /**
     * Gets the value of the bool property.
     * 
     */
    boolean isBool();

    /**
     * Sets the value of the bool property.
     * 
     */
    void setBool(boolean value);

    boolean isSetBool();

    java.io.Serializable getContent();

    boolean isSetContent();

    void unsetContent();


    /**
     * Java content class for model group.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/Works/TestJAXB_V1/bind-choice/example.xsd line 25)
     * <p>
     * <pre>
     * &lt;choice>
     *   &lt;element name="bool" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *   &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     * &lt;/choice>
     * </pre>
     * 
     */
    public interface BoolOrCommentOrValue {


        /**
         * Gets the value of the value property.
         * 
         */
        int getValue();

        /**
         * Sets the value of the value property.
         * 
         */
        void setValue(int value);

        boolean isSetValue();

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getComment();

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setComment(java.lang.String value);

        boolean isSetComment();

        /**
         * Gets the value of the bool property.
         * 
         */
        boolean isBool();

        /**
         * Sets the value of the bool property.
         * 
         */
        void setBool(boolean value);

        boolean isSetBool();

        java.io.Serializable getContent();

        boolean isSetContent();

        void unsetContent();

    }

}
