//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 10:54:55 PM IST 
//


package example;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends example.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static example.impl.runtime.GrammarInfo grammarInfo = new example.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (example.ObjectFactory.class));
    public final static java.lang.Class version = (example.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((example.ModelGroupChoice.class), "example.impl.ModelGroupChoiceImpl");
        defaultImplementations.put((example.FooBarType.PhoneNumberOrSpeedDial.class), "example.impl.FooBarTypeImpl.PhoneNumberOrSpeedDialImpl");
        defaultImplementations.put((example.FooBar.class), "example.impl.FooBarImpl");
        defaultImplementations.put((example.ModelGroupChoice.BoolOrCommentOrValue.class), "example.impl.ModelGroupChoiceImpl.BoolOrCommentOrValueImpl");
        defaultImplementations.put((example.FooBarType.class), "example.impl.FooBarTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "FooBar"), (example.FooBar.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: example
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ModelGroupChoice
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public example.ModelGroupChoice createModelGroupChoice()
        throws javax.xml.bind.JAXBException
    {
        return new example.impl.ModelGroupChoiceImpl();
    }

    /**
     * Create an instance of FooBarTypePhoneNumberOrSpeedDial
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public example.FooBarType.PhoneNumberOrSpeedDial createFooBarTypePhoneNumberOrSpeedDial()
        throws javax.xml.bind.JAXBException
    {
        return new example.impl.FooBarTypeImpl.PhoneNumberOrSpeedDialImpl();
    }

    /**
     * Create an instance of FooBar
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public example.FooBar createFooBar()
        throws javax.xml.bind.JAXBException
    {
        return new example.impl.FooBarImpl();
    }

    /**
     * Create an instance of ModelGroupChoiceBoolOrCommentOrValue
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public example.ModelGroupChoice.BoolOrCommentOrValue createModelGroupChoiceBoolOrCommentOrValue()
        throws javax.xml.bind.JAXBException
    {
        return new example.impl.ModelGroupChoiceImpl.BoolOrCommentOrValueImpl();
    }

    /**
     * Create an instance of FooBarType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public example.FooBarType createFooBarType()
        throws javax.xml.bind.JAXBException
    {
        return new example.impl.FooBarTypeImpl();
    }

}
